### ISSUE TITLE
Activity Date shift from AVDTH to T3R

### ISSUE THREAD

**Issue by Antoine-Duparc** [OB7-IRD/t3#79]
**Describe the bug**
every activity dates are shifted from one day (-1 day) in the T3R outputs (from step 1.1 and other). 

In the activity id the day is written in day of the year instead of the day of the month. I don't know whether this is linked because the day of the year seems good. 

**To Reproduce**
run T3R for a given year and check activity dates between AVDTH and output from step 1.1.

**correction to do**
1- correct the sql request to write the activity day in day of month.
2- find where the activity date is loaded from database or calculated and correct.

**Comment by MathieuDepetris** [comment]
Problem solved.
Troubles related are:
- in the avdth sql queries on the function format(activity_date, 'YYYYMMDD'). Format argument YYYYMMDD not give the expected value, due to the DD at the end. The argument was replaced by yyyymmdd. @laurentfloch it could be useful for you in the future.
- when you use the function as.Date() in R, if the argument associated is date with time and if time is equal to 0, the function convert the value to date minus 1 day. Replaced here by lubridate::ymd
