### ISSUE TITLE
Add activity location in output tables

### ISSUE THREAD

**Issue by Antoine-Duparc** [OB7-IRD/t3#90]
Juste a recall to add activity locations (lat and lon in decimal degree) in tables of the outputs for the level1 and also level 2 to help for user checking.

**Comment by MathieuDepetris** [comment]
@Antoine-Duparc, outputs of steps 1.1 to 1.6 has been updated with adding variables of localisation. So far I don't touch to the other steps because I'm not sure that is relevant (and more time consuming), but we can discuss that. I think you can finish what you want to do initially with theses updates.
